(ns clef.gen-script
  (:require [babashka.fs :as fs]
            [clojure.string :as str]))

(def template-root "resources/clj/new/clef")
(def templates-file "src/clef/templates.clj")

(defn- template-files
  "Map of {relative-path content} for every file under the template root,
   in sorted order for deterministic output."
  []
  (let [root (fs/file template-root)]
    (into (sorted-map)
          (for [f (filter fs/regular-file? (file-seq root))]
            [(str (fs/relativize root f)) (slurp f)]))))

(defn gen-templates!
  "Write src/clef/templates.clj, embedding every template file as a string
   literal so the single-file ./clef carries the templates with no
   filesystem dependency. pr-str makes the round-trip lossless."
  []
  (let [files   (template-files)
        entries (->> files
                     (map (fn [[path content]]
                            (str (pr-str path) "\n   " (pr-str content))))
                     (str/join "\n\n   "))
        src     (str "(ns clef.templates)\n\n"
                     ";; GENERATED by `bb gen-script` from " template-root "\n"
                     ";; Do not edit by hand.\n\n"
                     "(def files\n  {" entries "})\n")]
    (spit templates-file src)
    (println (str "Wrote " templates-file " (" (count files) " files)"))))

(defn gen-script
  "Generate src/clef/templates.clj, then concatenate clef's source
   namespaces into a single bb-runnable script at ./clef. Order matters:
   each namespace must precede the ones that require it."
  []
  (gen-templates!)
  (let [parts      [(slurp "prelude")
                    (slurp "src/clef/version.clj")
                    (slurp templates-file)
                    (slurp "src/clef/new.clj")
                    (slurp "src/clef/main.clj")
                    "(apply clef.main/-main *command-line-args*)"]
        script     (str/join "\n\n" parts)]
    (spit "clef" script)
    (.setExecutable (java.io.File. "clef") true)
    (println "Wrote ./clef")))
